name: Closed Issue Message
on:
    issues:
       types: [closed]
jobs:
    auto_comment:
        if: github.repository == 'aws/aws-sdk-java-v2'
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
        - name: Harden the runner
          uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
          with:
            use-policy-store: true
            api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

        - uses: aws-actions/closed-issue-message@v1
          with:
            # These inputs are both required
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            message: |
              This issue is now closed. Comments on closed issues are hard for our team to see.
              If you need more assistance, please open a new issue that references this one.
