name: HandleStaleDiscussions
on:
  schedule:
    - cron: '0 */4 * * *'
  discussion_comment:
    types: [created]

jobs:
  handle-stale-discussions:
    if: github.repository == 'aws/aws-sdk-java-v2'
    name: Handle stale discussions
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Stale discussions action
        uses: aws-github-ops/handle-stale-discussions@v1
        with:
          close-stale-as-answered: false
          close-answered-discussion: false
        env:
          GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
